# Generated by Django 5.2.17 on 2026-09-04 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clerk_user_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('driver_number', models.CharField(blank=True, max_length=7)),
                ('driver_full_name', models.CharField(blank=True, max_length=255)),
                ('truck_number', models.CharField(blank=True, max_length=50)),
                ('trailer_number', models.CharField(blank=True, max_length=50)),
                ('carrier_name', models.CharField(blank=True, max_length=255)),
                ('carrier_address', models.CharField(blank=True, max_length=500)),
                ('time_base', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
