# Generated by Django 5.2.17 on 2026-09-04 11:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('current_location_text', models.CharField(max_length=255)),
                ('pickup_location_text', models.CharField(max_length=255)),
                ('dropoff_location_text', models.CharField(max_length=255)),
                ('default_cycle_used_hours', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='driver_number',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Driver number must be exactly 7 digits.', regex='^\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='trailer_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Trailer number must be in T__ format, e.g. T123456.', regex='^T\\d+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='truck_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Truck/tractor number must be in P__ format, e.g. P123456.', regex='^P\\d+$')]),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location_text', models.CharField(max_length=255)),
                ('current_lat', models.FloatField()),
                ('current_lon', models.FloatField()),
                ('pickup_location_text', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lon', models.FloatField()),
                ('dropoff_location_text', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lon', models.FloatField()),
                ('current_cycle_used_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('trip_start_datetime', models.DateTimeField()),
                ('route_geometry', models.JSONField(blank=True, default=list)),
                ('distance_miles', models.FloatField(default=0)),
                ('driving_hours', models.FloatField(default=0)),
                ('total_days', models.IntegerField(default=1)),
                ('logs_generated', models.BooleanField(default=False)),
                ('driver_number_snapshot', models.CharField(blank=True, max_length=7)),
                ('driver_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('truck_number_snapshot', models.CharField(blank=True, max_length=20)),
                ('trailer_number_snapshot', models.CharField(blank=True, max_length=20)),
                ('carrier_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('carrier_address_snapshot', models.CharField(blank=True, max_length=500)),
                ('time_base_snapshot', models.CharField(blank=True, max_length=50)),
                ('shipping_document_number', models.CharField(blank=True, max_length=100)),
                ('shipper_name', models.CharField(blank=True, max_length=255)),
                ('commodity', models.CharField(blank=True, max_length=255)),
                ('co_driver_name', models.CharField(blank=True, default='N/A', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_order', models.IntegerField()),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], max_length=32)),
                ('stop_type', models.CharField(blank=True, choices=[('driving_leg', 'Driving leg'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel_stop', 'Fuel stop'), ('30min_break', '30-minute break'), ('10hr_rest', '10-hour rest'), ('34hr_restart', '34-hour restart')], max_length=32)),
                ('is_split_sleeper', models.BooleanField(default=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('start_lat', models.FloatField()),
                ('start_lon', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lon', models.FloatField()),
                ('remark_location_text', models.CharField(blank=True, max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='core.trip')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('day_number', models.IntegerField()),
                ('multi_day_flag', models.BooleanField(default=False)),
                ('driving_miles_today', models.FloatField(default=0)),
                ('truck_mileage_today', models.FloatField(default=0)),
                ('off_duty_minutes', models.IntegerField(default=0)),
                ('sleeper_berth_minutes', models.IntegerField(default=0)),
                ('driving_minutes', models.IntegerField(default=0)),
                ('on_duty_not_driving_minutes', models.IntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='core.trip')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
