# Generated by Django 5.2.17 on 2026-09-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trippreset_alter_user_driver_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleblock',
            name='distance_miles',
            field=models.FloatField(default=0),
        ),
    ]
