# Generated by Django 5.2.17 on 2026-09-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_trip_presets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='carrier_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='carrier_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driver_full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driver_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time_base',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trailer_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='truck_number',
        ),
    ]
